name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '55 15 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库
      uses: actions/checkout@v3

    - name: 下载配置文件
      run: |
        download_config() {
          local dir=$1
          local feeds_url=$2
          local config_url=$3
          mkdir -p "$dir"
          if ! wget -nv -t 3 -T 30 -O "$dir/feeds.conf" "$feeds_url"; then
            echo "❌ 下载 feeds.conf 失败: $feeds_url"
            exit 1
          fi
          if ! wget -nv -t 3 -T 30 -O "$dir/.config" "$config_url"; then
            echo "❌ 下载 .config 失败: $config_url"
            exit 1
          fi
        }

        # 小米R3G-v2配置
        download_config Xiaomi-R3Gv2 \
          https://fw0.koolcenter.com/iStoreOS/R3Gv2/feeds.conf \
          https://fw0.koolcenter.com/iStoreOS/R3Gv2/config.buildinfo

        # x86系列配置
        download_config x86 \
          https://fw0.koolcenter.com/iStoreOS/x86_64_efi/feeds.conf \
          https://fw0.koolcenter.com/iStoreOS/x86_64_efi/config.buildinfo

        download_config x86-alpha \
          https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/feeds.conf \
          https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/config.buildinfo

    - name: 同步到配置分支
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.REPO_DEPLOY_TOKEN }}
        publish_branch: configs
        publish_dir: .
        keep_files: false
        commit_message: "chore(config): Update Xiaomi R3Gv2 config"

    - name: 清理工作流记录
      if: always()
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 5
        token: ${{ secrets.GITHUB_TOKEN }}
